#!/bin/bash

set -e

EZMASTER_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

if [ "$1" == "" ]; then
  echo "make-version should be called with a parameter (major, minor, ...)"
  exit 1
fi

echo "---> Creating a new $1 version with npm version"
npm version $1
VERSION=$(cat $EZMASTER_PATH/package.json | jq -r .version)
echo "---> Patching docker-compose.yml (prod file) for using this version"
sed -i "s#\(image: inistcnrs/ezmaster:\)\([\.a-z0-9]\+\)#\1${VERSION}#g" docker-compose.yml
git commit docker-compose.yml -m "Release ${VERSION}"
git tag --force v${VERSION} $(git rev-parse HEAD)
echo "---> Now, do not forget to push your tags:"
echo "     git push ; git push --tags"