#!/bin/bash
#
# Script used to update the ezmaster version in the docker-compose.yml 
# called from npm version <patch|minor|major> (see package.json)
# $npm_package_version is filled by "npm version" stuff
# see https://docs.npmjs.com/misc/scripts
#

set -e

echo "---> Patching docker-compose.yml (prod file) for using this version ${npm_package_version}"
sed -i "s#\(image: inistcnrs/ezmaster:\)\([\.a-z0-9]\+\)#\1${npm_package_version}#g" docker-compose.yml
git add docker-compose.yml
